apiVersion: v1
kind: Pod
metadata:
  name: www
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /home
      name: home
    - mountPath: /git
      name: git
      readOnly: true
    - mountPath: /temp
      name: temp
  volumes:
  - name: home
    hostPath:
      path: /Users/Guest
  - name: git
    gitRepo:
      repository: https://github.com/vitongos/kubernetes-course.git
  - name: temp
    emptyDir: {}